import { Link } from 'react-router-dom';

const features = [
  {
    title: 'Lift',
    desc: 'Upward force generated by pressure difference between upper and lower surfaces of the airfoil.',
    color: 'from-green-500 to-emerald-600',
    icon: '⬆️'
  },
  {
    title: 'Drag',
    desc: 'Rearward force opposing motion, caused by air resistance and flow separation.',
    color: 'from-orange-500 to-red-500',
    icon: '⬅️'
  },
  {
    title: 'Angle of Attack',
    desc: 'Angle between the wing chord line and the relative wind. Critical for lift generation.',
    color: 'from-blue-500 to-indigo-600',
    icon: '📐'
  },
  {
    title: 'Velocity',
    desc: 'Speed of the airfoil relative to the air. Higher velocity increases both lift and drag (V²).',
    color: 'from-purple-500 to-pink-500',
    icon: '🚀'
  },
  {
    title: 'Airfoil Shape',
    desc: 'Cross-sectional shape that determines aerodynamic characteristics. Camber and thickness are key.',
    color: 'from-amber-500 to-orange-600',
    icon: '✈️'
  }
];

export default function Home() {
  return (
    <div className="min-h-screen">
      <div className="relative overflow-hidden bg-gradient-to-br from-blue-950 via-indigo-950 to-purple-950 text-white">
        <div className="absolute inset-0 opacity-[0.04]">
          <svg viewBox="0 0 1200 600" className="w-full h-full">
            <path d="M0,300 C200,200 400,400 600,250 C800,100 1000,300 1200,200 L1200,600 L0,600Z" fill="white" />
          </svg>
        </div>

        {/* Ambient particles */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          {[...Array(6)].map((_, i) => (
            <div key={i}
              className="absolute rounded-full"
              style={{
                width: `${80 + i * 60}px`,
                height: `${80 + i * 60}px`,
                left: `${15 + i * 14}%`,
                top: `${20 + i * 10}%`,
                background: `radial-gradient(circle, rgba(59,130,246,0.06), transparent)`,
                animation: `float ${4 + i * 0.5}s ease-in-out infinite`,
                animationDelay: `${i * 0.6}s`,
              }}
            />
          ))}
        </div>

        <div className="max-w-7xl mx-auto px-4 py-20 relative">
          <div className="text-center max-w-4xl mx-auto">
            <div className="text-6xl mb-6 animate-bounce-slow select-none">✈️</div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 animate-slideUp heading-gradient text-glow">
              Interactive Airfoil Lift & Drag Visualizer
            </h1>
            <p className="text-lg md:text-xl text-blue-200/80 mb-8 max-w-3xl mx-auto leading-relaxed">
              Explore how airfoil shape, velocity, and angle of attack affect lift and drag
              through interactive visualization and real-time calculations.
            </p>
            <div className="flex flex-wrap gap-4 justify-center mb-12">
              <Link to="/simulator" className="btn-primary text-lg px-8 py-3 no-underline inline-block">
                Start Simulation →
              </Link>
              <Link to="/custom" className="btn-secondary text-lg px-8 py-3 no-underline inline-block">
                Upload Custom Airfoil
              </Link>
            </div>
          </div>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-24 bg-gradient-to-t from-[var(--bg-primary)] to-transparent" />
      </div>

      <div className="max-w-7xl mx-auto px-4 py-12 -mt-8 relative">
        <div className="text-center mb-12">
          <h2 className="text-2xl md:text-3xl font-bold heading-gradient">Understanding Aerodynamics</h2>
          <p className="text-gray-500 mt-2">Explore the key concepts behind lift and drag generation</p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((f, i) => (
            <div key={i} className="group relative rounded-2xl p-6 animate-slideUp card"
              style={{ animationDelay: `${i * 100}ms` }}>
              <div className={`absolute inset-0 bg-gradient-to-br ${f.color} opacity-0 group-hover:opacity-[0.07] rounded-2xl transition-opacity duration-500`} />
              <div className="flex items-start gap-4 relative">
                <span className="text-3xl">{f.icon}</span>
                <div>
                  <h3 className="font-bold text-lg mb-1" style={{ color: 'var(--accent-blue)' }}>{f.title}</h3>
                  <p className="text-gray-400 text-sm leading-relaxed">{f.desc}</p>
                </div>
              </div>
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-2xl p-8 card">
          <h2 className="text-2xl font-bold mb-4 heading-gradient">About This Project</h2>
          <p className="text-gray-300 leading-relaxed mb-4">
            This interactive educational tool helps students understand how lift and drag
            are produced on different airfoils by changing input parameters and seeing
            real-time visual results. It combines aeronautical engineering principles with
            modern web technology to create an engaging learning experience.
          </p>
          <div className="notice-box">
            <strong>ℹ Note:</strong> Uses simplified aerodynamic approximations for educational visualization.
            Results are not CFD-accurate and should not be used for real aircraft design without validation.
          </div>
        </div>

        <div className="text-center mt-10 text-sm" style={{ color: 'var(--text-muted)' }}>
          <span className="text-xs tracking-widest uppercase opacity-60">Built with</span>
          <div className="mt-2 flex flex-wrap justify-center gap-3 text-xs" style={{ color: 'var(--text-secondary)' }}>
            <span className="badge-value">React</span>
            <span className="badge-value">Tailwind CSS</span>
            <span className="badge-value">Recharts</span>
            <span className="badge-value">Node.js</span>
            <span className="badge-value">Express</span>
          </div>
        </div>
      </div>
    </div>
  );
}
